import "@/app/globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { JetBrains_Mono } from "next/font/google";
export const metadata = {
  title: "Home",
  description: "Generated by Next.js home",
};

const jet = JetBrains_Mono({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={jet.className}>
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
        />
      </head>
      <body>
        <Navbar />
        <main className="h-screen py-20">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
