import Assignments from "@/components/dashboard/Assignments";
import Notifications from "@/components/dashboard/Notifications";
import Quiz from "@/components/dashboard/Quiz";

// import Image from "next/image";
export const metadata = {
  title: "Dashboard | Home",
  description: "Generated by Next.js Dashboard Home",
};
const DashboardPage = () => {
  return (
    <>
      <h1 className="text-3xl font-bold text-center">Welcome to the Dashboard</h1>
      {/* <Image src="https://images.pexels.com/photos/2325447/pexels-photo-2325447.jpeg" alt="img" width={500} height={500} /> */}
      <div className="grid gap-6 grid-cols-2 grid-rows-2 p-8">
        <Assignments />
        <Notifications />
        <Quiz/>
      </div>
    </>
  );
};

export default DashboardPage;
