import Image from "next/image";
export const metadata = {
  title: "Dashboard | Home",
  description: "Generated by Next.js Dashboard Home",
};
const DashboardPage = () => {
  return (
    <div>
      <h1>Welcome to the Dashboard</h1>
      <Image src="https://images.pexels.com/photos/2325447/pexels-photo-2325447.jpeg" alt="img" width={500} height={500} />
    </div>
  )
}

export default DashboardPage;