import Link from "next/link";
import { Poppins } from "next/font/google";
export const metadata = {
  title: "Dashboard",
  description: "Generated by Next.js Dashboard",
};
const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  style: "normal",
});

type Props = {
  children: React.ReactNode;
  assignments: React.ReactNode;
  notifications: React.ReactNode;
  quiz: React.ReactNode;
};

export default function ParallelDashboardLayout({
  children,
  assignments,
  notifications,
  quiz,
}: Props) {
  const isLoggedIn: boolean = true;
  return (
    <div className={`flex h-screen bg-gray-100 ${poppins.className}`}>
      <aside className="w-64 bg-white shadow-md">
        <div className="p-5">
          <Link href="/parallel-dashboard">
            <h2 className="text-2xl font-semibold text-gray-800">
              Parallel Dashboard
            </h2>
          </Link>
        </div>
        <nav className="mt-5">
          <Link
            href="/dashboard/settings"
            className="block py-3 px-5 text-gray-600 hover:bg-gray-100 hover:text-gray-900 transition-colors duration-200"
          >
            <i className="fas fa-cog mr-2"></i> Settings
          </Link>
          <Link
            href="/dashboard/profile"
            className="block py-3 px-5 text-gray-600 hover:bg-gray-100 hover:text-gray-900 transition-colors duration-200"
          >
            <i className="fas fa-user mr-2"></i> Profile
          </Link>
          <Link
            href="/dashboard/articles/breaking-news?lang=en"
            className="block py-3 px-5 text-gray-600 hover:bg-gray-100 hover:text-gray-900 transition-colors duration-200"
          >
            <i className="fas fa-language mr-2"></i> Read in English
          </Link>
          <Link
            href="/dashboard/articles/breaking-news?lang=bn"
            className="block py-3 px-5 text-gray-600 hover:bg-gray-100 hover:text-gray-900 transition-colors duration-200"
          >
            <i className="fas fa-language mr-2"></i> Read in Bangla
          </Link>
          <Link
            href="/dashboard/logout"
            className="block py-3 px-5 text-red-600 hover:bg-red-100 hover:text-red-900 transition-colors duration-200"
          >
            {" "}
            <i className="fas fa-sign-out-alt mr-2"></i> Logout
          </Link>
        </nav>
      </aside>
      <main className="flex-1 overflow-y-auto">
        <>
          <h1 className="text-3xl font-bold text-center pt-6">
            Welcome to the Parallel Dashboard
          </h1>
          {children}
          <div className="grid gap-6 grid-cols-2 grid-rows-2 p-8">
            {isLoggedIn && assignments}
            {notifications}
            {quiz}
          </div>
        </>
      </main>
    </div>
  );
}
