
export const metadata = {
  title: "Dashboard | Profile",
  description: "Generated by Next.js profile",
};
const ProfilePage = () => {
  return <div>Profile Page</div>;
};

export default ProfilePage;
